# Generated by Django 4.0.5 on 2022-06-20 12:55

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Store',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=64, verbose_name=' ')),
            ],
        ),
        migrations.CreateModel(
            name='Purchase',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(db_column='product', max_length=128, verbose_name=' ')),
                ('price', models.DecimalField(decimal_places=2, max_digits=10, verbose_name=', .')),
                ('store', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Storage.store', verbose_name='')),
            ],
        ),
    ]
